[colors.primary]
background = '#151310'
foreground = '#e8e1dc'
 
[colors.cursor]
text = '#e8e1dc'
cursor = '#d0c5b8' 
 
[colors.vi_mode_cursor]
text = '#151310'
cursor = '#f0d4ac' 
 
[colors.search.matches]
foreground = '#4d463c' 
background = '#cdd8f0' 
 
[colors.search.focused_match]
foreground = '#4d463c' 
background = '#f0d4ac' 
 
[colors.footer_bar]
foreground = '#4d463c' 
background = '#e8e1dc' 
 
[colors.hints.start]
foreground = '#4d463c' 
background = '#d3c4b2' 
 
[colors.hints.end]
foreground = '#4d463c' 
background = '#d3c4b2' 
 
[colors.selection]
text = '#151310'
background = '#f0d4ac'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#f0d4ac' 
yellow = '#705b3b' 
blue = '#f0d4ac' 
magenta = '#cdd8f0' 
cyan = '#d3c4b2' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
