[colors.primary]
background = '#131312'
foreground = '#e5e2e0'
 
[colors.cursor]
text = '#e5e2e0'
cursor = '#c6c7bf' 
 
[colors.vi_mode_cursor]
text = '#131312'
cursor = '#c3c8ba' 
 
[colors.search.matches]
foreground = '#454841' 
background = '#bec9c9' 
 
[colors.search.focused_match]
foreground = '#454841' 
background = '#c3c8ba' 
 
[colors.footer_bar]
foreground = '#454841' 
background = '#e5e2e0' 
 
[colors.hints.start]
foreground = '#454841' 
background = '#c6c7c0' 
 
[colors.hints.end]
foreground = '#454841' 
background = '#c6c7c0' 
 
[colors.selection]
text = '#131312'
background = '#c3c8ba'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#c3c8ba' 
yellow = '#5b6054' 
blue = '#c3c8ba' 
magenta = '#bec9c9' 
cyan = '#c6c7c0' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
