[colors.primary]
background = '#151310'
foreground = '#e8e1dc'
 
[colors.cursor]
text = '#e8e1dc'
cursor = '#cfc5b8' 
 
[colors.vi_mode_cursor]
text = '#151310'
cursor = '#dcc399' 
 
[colors.search.matches]
foreground = '#4c463c' 
background = '#bfcba6' 
 
[colors.search.focused_match]
foreground = '#4c463c' 
background = '#dcc399' 
 
[colors.footer_bar]
foreground = '#4c463c' 
background = '#e8e1dc' 
 
[colors.hints.start]
foreground = '#4c463c' 
background = '#d2c5b0' 
 
[colors.hints.end]
foreground = '#4c463c' 
background = '#d2c5b0' 
 
[colors.selection]
text = '#151310'
background = '#dcc399'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#dcc399' 
yellow = '#6e5c39' 
blue = '#dcc399' 
magenta = '#bfcba6' 
cyan = '#d2c5b0' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
