[colors.primary]
background = '#111415'
foreground = '#e1e3e3'
 
[colors.cursor]
text = '#e1e3e3'
cursor = '#bfc8ca' 
 
[colors.vi_mode_cursor]
text = '#111415'
cursor = '#90d1de' 
 
[colors.search.matches]
foreground = '#3f484a' 
background = '#dabbf1' 
 
[colors.search.focused_match]
foreground = '#3f484a' 
background = '#90d1de' 
 
[colors.footer_bar]
foreground = '#3f484a' 
background = '#e1e3e3' 
 
[colors.hints.start]
foreground = '#3f484a' 
background = '#b2cbd0' 
 
[colors.hints.end]
foreground = '#3f484a' 
background = '#b2cbd0' 
 
[colors.selection]
text = '#111415'
background = '#90d1de'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#90d1de' 
yellow = '#206773' 
blue = '#90d1de' 
magenta = '#dabbf1' 
cyan = '#b2cbd0' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
