[colors.primary]
background = '#121414'
foreground = '#e2e2e2'
 
[colors.cursor]
text = '#e2e2e2'
cursor = '#c0c8c7' 
 
[colors.vi_mode_cursor]
text = '#121414'
cursor = '#a4cfcd' 
 
[colors.search.matches]
foreground = '#404848' 
background = '#f1bba3' 
 
[colors.search.focused_match]
foreground = '#404848' 
background = '#a4cfcd' 
 
[colors.footer_bar]
foreground = '#404848' 
background = '#e2e2e2' 
 
[colors.hints.start]
foreground = '#404848' 
background = '#b9cac9' 
 
[colors.hints.end]
foreground = '#404848' 
background = '#b9cac9' 
 
[colors.selection]
text = '#121414'
background = '#a4cfcd'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#a4cfcd' 
yellow = '#3d6564' 
blue = '#a4cfcd' 
magenta = '#f1bba3' 
cyan = '#b9cac9' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
