[colors.primary]
background = '#131314'
foreground = '#e4e2e2'
 
[colors.cursor]
text = '#e4e2e2'
cursor = '#c2c7c8' 
 
[colors.vi_mode_cursor]
text = '#131314'
cursor = '#dff2f4' 
 
[colors.search.matches]
foreground = '#424848' 
background = '#ffeae3' 
 
[colors.search.focused_match]
foreground = '#424848' 
background = '#dff2f4' 
 
[colors.footer_bar]
foreground = '#424848' 
background = '#e4e2e2' 
 
[colors.hints.start]
foreground = '#424848' 
background = '#c1c8c8' 
 
[colors.hints.end]
foreground = '#424848' 
background = '#c1c8c8' 
 
[colors.selection]
text = '#131314'
background = '#dff2f4'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#dff2f4' 
yellow = '#506263' 
blue = '#dff2f4' 
magenta = '#ffeae3' 
cyan = '#c1c8c8' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
